/* tslint:disable */

/**
 * Binance Web3 API
 *
 * Cross-chain wallet, market, trading, transaction, and B402 payment APIs for the Binance Web3 API platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Underlying asset market data. Fields vary by asset type.
 * @export
 * @interface GetRwaUnderlyingMarketDataResponseDataMarketData
 */
export interface GetRwaUnderlyingMarketDataResponseDataMarketData {
    /**
     * Underlying reference price (USD). A per-share converted price derived from the on-chain token price, not an official quote from the traditional stock market.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    referencePrice?: string;
    /**
     * 52-week high price. Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    high52W?: string;
    /**
     * 52-week low price. Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    low52W?: string;
    /**
     * 24-hour trading volume in shares.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    volumeShares24H?: string;
    /**
     * 1-year average daily volume. Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    avgDailyVolume1Y?: string;
    /**
     * Total outstanding shares (Stock) or total units (ETF). Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    totalShares?: string;
    /**
     * Market capitalization (USD) for Stock/ETF, or implied total valuation for Pre-IPO.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    marketCap?: string;
    /**
     * Turnover rate. \"23.81\" means 23.81%. Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    turnoverRate?: string;
    /**
     * Price amplitude (intraday). \"3.05\" means 3.05%, i.e. (intraday high − low) / previous close. Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    amplitude?: string | null;
    /**
     * Price-to-Earnings ratio (TTM = Trailing Twelve Months, based on earnings of the most recent 12 months). Applicable to Stock only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    peRatioTTM?: string | null;
    /**
     * Price-to-Book ratio. Applicable to Stock only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    pbRatio?: string | null;
    /**
     * Dividend yield. \"0.85\" means 0.85%. Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    dividendYield?: string | null;
    /**
     * Latest dividend amount (USD). Applicable to Stock and ETF only.
     * @type {string}
     * @memberof GetRwaUnderlyingMarketDataResponseDataMarketData
     */
    latestDividend?: string | null;
}
